name: embedded
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  dotenv: ^4.1.0

dev_dependencies: 
  test: ^1.21.0
  very_good_analysis: ^5.1.0
