name: suda_website
description: Sistema Universal de Desefa Apocalíptico.
version: 1.0.0
repository: https://github.com/pedrohaveloso/suda

environment:
  sdk: ^3.1.3

dependencies:
  deact: ^1.5.1
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6
  very_good_analysis: ^5.1.0